# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.3

before_install:
  - gem install cocoapods
  - gem install xcpretty -N
  - brew update
script:
  - set -o pipefail
  # example
  - xcodebuild clean build -enableCodeCoverage YES -project VerticalCardSwiper.xcodeproj -scheme Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  # library
  - xcodebuild clean build -enableCodeCoverage YES -project VerticalCardSwiper.xcodeproj -scheme VerticalCardSwiper -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  # UI Tests
  - xcodebuild clean test -enableCodeCoverage YES -project VerticalCardSwiper.xcodeproj -scheme VerticalCardSwiperUITests -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  - pod lib lint